### ISSUE TITLE
Villager duplication

### ISSUE THREAD

**Issue by FistandanBitus** [toxuin/Griswold#10]
The plugin works great with a limited amount of blacksmiths and enchanters, but after about six blacksmiths, they start to duplicate as normal villagers with the same name.

**Comment by Noket** [comment]
@toxuin ... I can confirm this is a problem. The blacksmiths aren't being removed then the server restarts.

When the server restarts, they're just normal villagers.

**Comment by toxuin** [comment]
Couldn't reproduce. Stopping and starting server with 8 npcs in different chunks – everything seems to work fine, debug messages fire in time indicating npcs being loaded and unloaded.

Several times I've seen reports for this error when admin forces bukkit to stop or crashes server. I'll add some code to remove possible duplicated entities, but that's not a silver bullet.

Another case when this can happen is when some other plugins interfere with mob logic or chunk loading mechanics.

Anyways, I have pushed duplicate finder to repo now. It should be able to handle even those weird scenarios. Get it [at releases section](https://github.com/toxuin/Griswold/releases/tag/v0.075-dev) and let me know how did it go.

Thanks for the feedback!

**Comment by Haarolean** [comment]
Probly code stopped working at some point because of changes in bukkit or something else, or even didn't work. I've fixed it again, dummy repairmen will be removed now. Consider adjusting "DuplicateFinderRadius" in config if needed, I used 20 during testing, was enough for almost every duplicated villager.
