### ISSUE TITLE
error with enchantments 

### ISSUE THREAD

**Issue by Darkool** [toxuin/Griswold#12]
Hi i have an issue with enchantments on minecraft 1.8 
http://pastebin.com/07n0RSSP

can you help me?

**Comment by Noket** [comment]
1.8 switched from players to uuids. Many of the methods that dealt with
handling players were made invalid, and replaced by methods in the
OfflinePlayer class. If his plugin hasn't updated to use these new methods,
then it will certainly throw a NPE.

Also, are you using spigot 1.8 or craftbukkit? I'm pretty sure he compiles
his code against craftbukkit

**Comment by Darkool** [comment]
Im using spigot 1.8

**Comment by Noket** [comment]
Updating this plugin has been on my list of things to do. I'll see about
refactoring his project (it doesn't seem to play nice with maven). If
(when) I get it updated, I'll make sure to reply to this email.

@toxuin .. would you like help working on this plugin? or is it abandoned?

Cheers

**Comment by toxuin** [comment]
I'm not currently working on new version of Griswold since all the Bukkit DMCA thing happened. But if you need this plugin working – I'll update it, no problem. I'll post update once I'll have something to show.

**Comment by toxuin** [comment]
Okay, that was kinda easier than I thought. Commit ff8de1d1e6d69b89a1d2bbc30d16074c767553f1 should make Griswold 1.8-compatible. Could you please test and post your results here? [Here is a test build](https://github.com/toxuin/Griswold/releases/tag/v0.75-dev).

Thanks!

**Comment by Darkool** [comment]
Oh toxuin, really thanks a lot, excelent plugin, works fine with SPIGOT 1.8, greetings!

**Comment by Noket** [comment]
Dude, you rock. Thanks for taking the time to do this.

Do you still not have a minecraft account, btw?

**Comment by toxuin** [comment]
Ah, no worries. It turned out that 1.8 break was not because of bukkit, but because one class in minecraft itself got renamed.

Yeah, no account. But I don't play a lot lately – minecraft taught me java and java brought me to android.

**Comment by Haarolean** [comment]
Fixed I guess?
