### ISSUE TITLE
Cauldron 1.7.10 

### ISSUE THREAD

**Issue by c4eva** [toxuin/Griswold#13]
First many Mod Items doesnt work with that plugin? It always says: I cant repair that.
Do u have a version for 1.7.10 Cauldron ? Cause the current one doesnt work. I use the 1.7.2 right now 
without any problems.

I hope u can help me.

**Comment by Haarolean** [comment]
Is a problem with mods' items and your Cauldron version linked or are these different problems? 
Do you have any errors in console with 1.7.10 version?

**Comment by Haarolean** [comment]
Okay, no answer provided so I'll close this one. Anyway, we're working on 1.12 support right now.
