### ISSUE TITLE
Dont repair unbreakable item

### ISSUE THREAD

**Issue by prozhong** [toxuin/Griswold#17]
https://www.spigotmc.org/wiki/custom-item-models-in-1-9-and-up/

https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/meta/ItemMeta.html#setUnbreakable(boolean)

some plugins introduce some items which are unbreakable, if repaired their custom model will change.

Could you please add an option to disable repairing unbreakable item?

**Comment by Haarolean** [comment]
Hey there, I'll look into that.

**Comment by Haarolean** [comment]
Hey, test this out: https://github.com/toxuin/Griswold/releases/tag/v0.078
Haven't published this anywhere yet, lemme know if that works or not.

**Comment by prozhong** [comment]
https://github.com/toxuin/Griswold/blob/master/src/com/github/toxuin/griswold/Interactor.java#L339
This line of code won't be reached, unless that repairman's RepairerType is undefined

**Comment by Haarolean** [comment]
Smh, didn't even pay attention. 
Try [this one](https://github.com/toxuin/Griswold/releases/tag/v0.079)

**Comment by Haarolean** [comment]
@prozhong I'm waiting for some feedback from you, if that works I'm gonna upload this to bukkitdev+spigot

**Comment by prozhong** [comment]
sorry for my late reply
with version 0.079 I can still repair my durability = 10 & unbreakable custom model weapon
maybe could you consider fix it like this ?https://github.com/prozhong/Griswold/commit/38a5bdc2f34aced625efc95d4da5aab373997aef
just do more check if config has option like 'dont-repair-and-enchant-unbreakable = true'

**Comment by Haarolean** [comment]
There's no need for an additional config key if it can be avoided.
The commit you provided - does it work for you? This particular method
checks permissions mostly, I've added the same check in a proper place.
Can you share some plugin which adds such items?

29 дек. 2017 г. 4:14 пользователь "prozhong" <notifications@github.com>
написал:

**Comment by prozhong** [comment]
use RPGitems to create this kind of item
see https://github.com/NyaaCat/RPGitems-reloaded/issues/197

**Comment by Haarolean** [comment]
So does it work for you with https://github.com/prozhong/Griswold/commit/38a5bdc2f34aced625efc95d4da5aab373997aef? Have you tested your own build?

**Comment by toxuin** [comment]
Hi all.

This should now be fixed in release 0.079 along with other stuff.

[Release 0.079](https://github.com/toxuin/Griswold/releases/tag/0.079)

@prozhong, since you're our beta-tester here now (🥇), please test this release in your setup and let us know. I've tested it on my local installation and it seems to work, but my setup is probably much simpler than yours anyways.

Please let us know if you find any more bugs or have any comments/suggestions/wishes.

**Comment by prozhong** [comment]
![griswold](https://user-images.githubusercontent.com/1495642/34451534-8cc94c1e-ed63-11e7-9c5e-5705b06c1c53.png)
@toxuin @Haarolean Release 0.079 fixs this issue, thanks 

https://imgur.com/a/7nNsd
this is my temp fix, but yours are better, I think
👍
