### ISSUE TITLE
Citizens2 Trait support

### ISSUE THREAD

**Issue by prozhong** [toxuin/Griswold#18]
Could you please add a new way to create blacksmith:

I add a trait 'bsmith_all' to a citizens2 npc, then he can repair and enchant item

just like plugin Morefish does: 
https://github.com/elsiff/MoreFish/blob/master/src/main/java/me/elsiff/morefish/hooker/FishShopTrait.java
https://github.com/elsiff/MoreFish/blob/master/src/main/java/me/elsiff/morefish/hooker/CitizensHooker.java

**Comment by toxuin** [comment]
This, as well as other plugins integrations, are certainly on the roadmap.

I would think your server is of an RPG theme. Would you suggest any other plugins you’d like to see integration with?

**Comment by Haarolean** [comment]
@prozhong so, do you want to use Citizens' npcs with skins and stuff with Griswold' features, right? If that's right - sounds good, not a big deal. We'll work on it after the holidays.

**Comment by prozhong** [comment]
@Haarolean Yes and Citizens's npc won't be pushed by players and won't be affected by worldguard's 'mob-spawning=deny' limit

**Comment by toxuin** [comment]
@prozhong There is a PR [#19](https://github.com/toxuin/Griswold/pull/19) in place that adds support for citizens. I hope you know how to build this.

**Comment by prozhong** [comment]
@toxuin It works fine... I can repair 
However everytime I rightclick the npc, the console prints 2 lines like this
`[14:03:48] [Server thread/ERROR]: [Citizens] Cannot register a null trait. Was it registered properly?`
`[14:03:48] [Server thread/ERROR]: [Citizens] Cannot register a null trait. Was it registered properly?`

seems Citizens doesn't think the trait is registered, so weird

More info
I can add trait "griswold_tools" but can not remove it
![nj8klc6et ap6 qvq 3tgfe](https://user-images.githubusercontent.com/1495642/34459776-dc74a8b8-ee34-11e7-930d-44b0a99e1db8.png)

**Comment by toxuin** [comment]
Which version of Citizens are you on? Which version of Bukkit/Spigot? I cannot reproduce this on my setup.

**Comment by prozhong** [comment]
This server is running Paper version git-Paper-1104 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

Citizens version 2.0.22-SNAPSHOT (build 1487)

**Comment by toxuin** [comment]
I have tested this branch with your exact versions and I still cannot observe same errors. The only thing I could see being different is locale.

If you would like to try out my build – meet me on Griswold's [Gitter](https://gitter.im/toxuin/Griswold) channel.

**Comment by Haarolean** [comment]
@prozhong Try to avoid hieroglyphs in the names for testing purposes

**Comment by prozhong** [comment]
Citizens v2.0.22.jar
Essentials-2.x-SNAPSHOT.jar
Griswold-5a033b8.jar
Vault.jar

I tested with this 4 plugins and found that if only there are essentials & vault together,
the 'Cannot register a null trait' error will occur

**Comment by prozhong** [comment]
weird
![image](https://user-images.githubusercontent.com/1495642/34474091-4c08216a-efb5-11e7-813e-b623554e84c9.png)
I used the same plugins & paper#1104
added a griswold_both trait to it,
right-clicked it (worked but there were 2 error in console) 
and removed the trait successfully

this is my jars
https://www.dropbox.com/s/u4auuhalf788ul9/lite.zip?dl=0

**Comment by toxuin** [comment]
@prozhong I've just pushed some changes to PR that should fix null-trait message. Please test.

**Comment by prozhong** [comment]
@toxuin The 'Cannot register a null trait' error disappeared

**Comment by prozhong** [comment]
I think we can mark this closed after the PR get merged
